name: ci-node-workflow
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  pull_request:
    branches:
      - master
      - develop
      - release
  workflow_dispatch:

jobs:
  check-application:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - name: Install Dependencies
          run: npm ci
        - name: Run Tests
          run: npm test